[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.110.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
    GO_VERSION = "1.20"
    PYTHON_VERSION = "3.8"
    NODE_VERSION = "18"